### ISSUE TITLE
社区规范--草案

### ISSUE THREAD

**Issue by ahbing** [hdufe/hdufe.github.io#1]
# 为什么做这个社区？
- 这个时代总是要懂点技术的，前端就是一个很好的切入口，而且它的趋势越来越火，越来越多元化。
- 网上现有的社区其实已经有很多了，例如: CNode、前端网、前端乱炖等。相比较它们而言，hdufe的主旨是
  - 联合杭电开发者（不仅限于前端）
  - 营造良好的开发者氛围
  - 整顿适合我们的资源
  - 校园代码开源化
  - 挖掘大神
  - 极客精神
  - 引导
  - 家
- 社区的知识沉淀，增加搜索方案 “关键字 site:hdufe.betahouse.us” 可能更快获得适合你的结果。创造/传播更适合杭电的现有开发者和潜在开发者的信息。
- 宣传**人人为我，我为人人**的开放友爱的社区文化，享受别人的记录总结带来的知识和信息，同时也将自己的总结分享。
  - 分享一个问题
  - 分享一个细节
  - 分享一个笑话
  - 分享一个活动
  - 等等等等等等
- 如果有一个地方对开发者来说是家的话，那一定是社区了，
  - 社区使得杭电现有开发者交流更加紧密，更加有归属感，可以看到校园同学们在关注什么。
  - 社区的文化基调使得探讨过程更加细致，结果严谨。
- 组织聚会
  - 由社区发起，面向杭电的任何层次的分享交流会。
# 社区文化
- 聚会
- 头脑风暴
- 技术交流
- 技术、思想的分享
- 我们都是 hdufer
# 遇到问题？
1. 自我思考  ===> 总结分享
2. 科学搜索  ===> 已有结果/相关研究 ===> 总结分享
3. 提出问题  ===> 交流探讨 ===> 记录分享
## 技术搜索？
- google
- stackoverflow
- github
- segmentfault
- zhihu
- ...
# 问答格式

**在提出问题之前，请先尝试搜索**
## 问题标题
- 应该尽可能的**精准简练**，对于专业术语使用通用格式，如 `JavaScript` 不应该写成 `javascript` 或者 `js`。
## 问题内容
- 问题描述的信息应该**准确，简练**
- 应尽可能详细
- 应该使得其他同学可以快速理解。
## 问题的回答
- 回答要负责
- 回答[不要模棱两可](https://zh.wikipedia.org/wiki/Wikipedia:%E4%B8%8D%E8%A6%81%E6%A8%A1%E7%A8%9C%E5%85%A9%E5%8F%AF)。
- 回答引用内容应该[注明其出处](https://zh.wikipedia.org/wiki/Wikipedia:%E5%88%97%E6%98%8E%E6%9D%A5%E6%BA%90)。
- 回答的内容应该准备，对没有把握的知识，应该先进行查证。
# 文章分享
## 文章标题
- 应该尽可能的**精准简练**，对于专业术语使用通用格式，如 `JavaScript` 不应该写成 `javascript` 或者 `js`。
## 文章内容
- [不要华而不实](https://zh.wikipedia.org/wiki/Wikipedia:%E6%A0%BC%E5%BC%8F%E6%89%8B%E5%86%8A/%E4%B8%8D%E8%A6%81%E8%8F%AF%E8%80%8C%E4%B8%8D%E5%AF%A6)
- 文章引用内容应该[注明其出处](https://zh.wikipedia.org/wiki/Wikipedia:%E5%88%97%E6%98%8E%E6%9D%A5%E6%BA%90)。
- 每一篇文章必定是作者花费一定的时间精力写出的，要保证内容的真实性、严谨性。
## 关爱新手

参考 [不要伤害新手](https://zh.wikipedia.org/wiki/Wikipedia:%E4%B8%8D%E8%A6%81%E4%BC%A4%E5%AE%B3%E6%96%B0%E6%89%8B)
- 充分认识新手的价值，新鲜血液的加入可能给社区带来更多的知识，观点，想法。
- 新手犯错，应当使用谦虚的语气，让他们感到自己是真正受欢迎的，而不要让他们觉得所作所为都要通过那些完美主义者的苛责。
- 请必须了解到： 您曾经也是新手。
## 尊重
- 尊重每一个同学及其所创造的价值，对社区的同学报以[友爱](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BB%B4%E5%9F%BA%E5%8F%8B%E7%88%B1)的态度, 不进行[人身攻击](https://zh.wikipedia.org/wiki/Wikipedia:%E4%B8%8D%E8%A6%81%E4%BA%BA%E8%BA%AB%E6%94%BB%E5%87%BB)。
- 对社区同学回答，文章进行分享时添加引用出处。尊重每一个同学的原创内容。
- 客观理性的评价

**Comment by looading** [comment]
适当的调整了结构、并进行了相应的补充

**Comment by looading** [comment]
# 为什么做这个社区？

- 这个时代总是要懂点技术的，前端就是一个很好的切入口，而且它的趋势越来越火，越来越多元化。

- 网上现有的社区其实已经有很多了，例如: CNode、前端网、前端乱炖等。相比较它们而言，hdufe的主旨是
  - 联合杭电开发者（不仅限于前端）
  - 营造良好的开发者氛围
  - 整顿适合我们的资源
  - 校园代码开源化
  - 挖掘大神
  - 极客精神
  - 引导
  - 家


- 社区的知识沉淀，增加搜索方案 “关键字 site:hdufe.betahouse.us” 可能更快获得适合你的结果。创造/传播更适合杭电的现有开发者和潜在开发者的信息。

- 宣传**人人为我，我为人人**的开放友爱的社区文化，享受别人的记录总结带来的知识和信息，同时也将自己的总结分享。
  - 分享一个问题
  - 分享一个细节
  - 分享一个笑话
  - 分享一个活动
  - 等等等等等等


- 如果有一个地方对开发者来说是家的话，那一定是社区了，
  - 社区使得杭电现有开发者交流更加紧密，更加有归属感，可以看到校园同学们在关注什么。
  - 社区的文化基调使得探讨过程更加细致，结果严谨。


- 组织聚会
  - 由社区发起，面向杭电的任何层次的分享交流会。

# 社区文化

- 聚会

- 头脑风暴

- 技术交流

- 技术、思想的分享

- 我们都是 hdufer



# 遇到问题？

1. 自我思考  ===> 总结分享

2. 科学搜索  ===> 已有结果/相关研究 ===> 总结分享

3. 提出问题  ===> 交流探讨 ===> 记录分享

## 技术搜索？

- google

- stackoverflow

- github

- segmentfault

- zhihu

- ...




# 问答格式

**在提出问题之前，请先尝试搜索**

## 问题标题

- 应该尽可能的**精准简练**，对于专业术语使用通用格式，如 `JavaScript` 不应该写成 `javascript` 或者 `js`。

## 问题内容

- 问题描述的信息应该**准确，简练**

- 应尽可能详细

- 应该使得其他同学可以快速理解。

## 问题的回答

- 回答要负责

- 回答[不要模棱两可](https://zh.wikipedia.org/wiki/Wikipedia:%E4%B8%8D%E8%A6%81%E6%A8%A1%E7%A8%9C%E5%85%A9%E5%8F%AF)。

- 回答引用内容应该[注明其出处](https://zh.wikipedia.org/wiki/Wikipedia:%E5%88%97%E6%98%8E%E6%9D%A5%E6%BA%90)。

- 回答的内容应该准备，对没有把握的知识，应该先进行查证。



# 文章分享

## 文章标题

- 应该尽可能的**精准简练**，对于专业术语使用通用格式，如 `JavaScript` 不应该写成 `javascript` 或者 `js`。

## 文章内容

- [不要华而不实](https://zh.wikipedia.org/wiki/Wikipedia:%E6%A0%BC%E5%BC%8F%E6%89%8B%E5%86%8A/%E4%B8%8D%E8%A6%81%E8%8F%AF%E8%80%8C%E4%B8%8D%E5%AF%A6)

- 文章引用内容应该[注明其出处](https://zh.wikipedia.org/wiki/Wikipedia:%E5%88%97%E6%98%8E%E6%9D%A5%E6%BA%90)。

- 每一篇文章必定是作者花费一定的时间精力写出的，要保证内容的真实性、严谨性。


## 关爱新手 

参考 [不要伤害新手](https://zh.wikipedia.org/wiki/Wikipedia:%E4%B8%8D%E8%A6%81%E4%BC%A4%E5%AE%B3%E6%96%B0%E6%89%8B)

- 充分认识新手的价值，新鲜血液的加入可能给社区带来更多的知识，观点，想法。

- 新手犯错，应当使用谦虚的语气，让他们感到自己是真正受欢迎的，而不要让他们觉得所作所为都要通过那些完美主义者的苛责。

- 请必须了解到： 您曾经也是新手。

## 尊重

- 尊重每一个同学及其所创造的价值，对社区的同学报以[友爱](https://zh.wikipedia.org/wiki/Wikipedia:%E7%BB%B4%E5%9F%BA%E5%8F%8B%E7%88%B1)的态度, 不进行[人身攻击](https://zh.wikipedia.org/wiki/Wikipedia:%E4%B8%8D%E8%A6%81%E4%BA%BA%E8%BA%AB%E6%94%BB%E5%87%BB)。

- 对社区同学回答，文章进行分享时添加引用出处。尊重每一个同学的原创内容。

- 客观理性的评价

**Comment by looading** [comment]
做了以下修改
- 完善社区文化内容
- 突出并完善社区的目的
- 修改相应格式，条例更清晰些
