### ISSUE TITLE
关于站点迁移及域名问题

### ISSUE THREAD

**Issue by looading** [hdufe/hdufe.github.io#3]
# 服务器问题
由于原先的服务器到期，并且不归属于我们。因此之前的数据无法迁移。

目前暂时将站点迁移到我的服务器上。

# 域名问题
本来是已经拥有一个已备案的域名，但是不知道是什么原因，突然被通知要求备案。
因此暂时先用王侃提供的域名[http://cty.wkwfyf.com]暂时使用。
由于本服务器上有其他服务运行着，域名只有一个，因此没有对此站点进行反向代理。

# 现状
论坛已经正常跑起来了，地址为 http://cty.wkwfyf.com:9803/
关于以上问题，后期会解决，数据汇全部保留。

**Comment by ahbing** [comment]
好的

**Comment by laoqiren** [comment]
收到
